// @generated by codegen/generate-all.ts. DO NOT EDIT.
import type {
  RestClientProvider,
  RestClientTypeMap,
  RestClientVersion,
} from "./rest-client-type-map.ts";
import type { RestClient, RestClientOptions } from "./runtime/mod.ts";

type RestClientConfiguration = RestClientOptions | RestClient;

type RestClientLoader = (configuration: RestClientConfiguration) => Promise<unknown>;

const restClientLoaders = {
  "azure-devops": {
    "latest": async (options) =>
      new (await import("./azure-devops/latest/mod.ts")).AzureDevOpsRestClient(options),
  },
  "bitbucket": {
    "latest": async (options) =>
      new (await import("./bitbucket/latest/mod.ts")).BitbucketRestClient(options),
  },
  "codeberg": {
    "latest": async (options) =>
      new (await import("./codeberg/latest/mod.ts")).CodebergRestClient(options),
  },
  "gitea": {
    "1.26.4": async (options) =>
      new (await import("./gitea/1.26.4/mod.ts")).GiteaRestClient(options),
    "1.27.2": async (options) =>
      new (await import("./gitea/1.27.2/mod.ts")).GiteaRestClient(options),
  },
  "github": {
    "latest": async (options) =>
      new (await import("./github/latest/mod.ts")).GitHubRestClient(options),
  },
  "gitlab": {
    "18.11.11": async (options) =>
      new (await import("./gitlab/18.11.11/mod.ts")).GitLabRestClient(options),
    "19.3.1": async (options) =>
      new (await import("./gitlab/19.3.1/mod.ts")).GitLabRestClient(options),
  },
} satisfies Record<RestClientProvider, Record<string, RestClientLoader>>;

export function createProviderClient<
  const TProvider extends RestClientProvider,
  const TVersion extends RestClientVersion<TProvider>,
>(
  provider: TProvider,
  version: TVersion,
  baseUrl: string | URL,
): Promise<RestClientTypeMap[TProvider][TVersion]>;
export function createProviderClient<
  const TProvider extends RestClientProvider,
  const TVersion extends RestClientVersion<TProvider>,
>(
  provider: TProvider,
  version: TVersion,
  configuration: RestClientConfiguration,
): Promise<RestClientTypeMap[TProvider][TVersion]>;
export function createProviderClient<
  const TProvider extends RestClientProvider,
  const TVersion extends RestClientVersion<TProvider>,
>(
  provider: TProvider,
  version: TVersion,
  baseUrlOrConfiguration: string | URL | RestClientConfiguration,
): Promise<RestClientTypeMap[TProvider][TVersion]> {
  const loader = (restClientLoaders[provider] as Record<string, RestClientLoader>)[version];
  if (loader === undefined) {
    throw new Error(`Unknown provider client version ${provider} ${version}`);
  }
  let configuration: RestClientConfiguration;
  if (typeof baseUrlOrConfiguration === "string" || baseUrlOrConfiguration instanceof URL) {
    configuration = { baseUrl: baseUrlOrConfiguration };
  } else {
    configuration = baseUrlOrConfiguration;
  }
  return loader(configuration) as Promise<RestClientTypeMap[TProvider][TVersion]>;
}
