// @generated by codegen/generate-all.ts. DO NOT EDIT.
import type { RestClientProvider, RestClientVersion } from "./rest-client-type-map.ts";

export type GitHost = RestClientProvider;
export type GitHostVersion<TGitHost extends GitHost> = RestClientVersion<TGitHost>;

/** Public compatibility name for a Git host. */
export type Provider = GitHost;
/** Public compatibility name for a Git-host API version. */
export type ProviderVersion<TProvider extends Provider> = GitHostVersion<TProvider>;
