// @generated by codegen/generate-all.ts. DO NOT EDIT.
export type RestClientTypeMap = {
  "azure-devops": {
    "latest": import("./azure-devops/latest/mod.ts").AzureDevOpsRestClient;
  };
  "bitbucket": {
    "latest": import("./bitbucket/latest/mod.ts").BitbucketRestClient;
  };
  "codeberg": {
    "latest": import("./codeberg/latest/mod.ts").CodebergRestClient;
  };
  "forgejo": {
    "15.0.7": import("./forgejo/15.0.7/mod.ts").ForgejoRestClient;
    "16.0.3": import("./forgejo/16.0.3/mod.ts").ForgejoRestClient;
  };
  "gitea": {
    "1.26.4": import("./gitea/1.26.4/mod.ts").GiteaRestClient;
    "1.27.2": import("./gitea/1.27.2/mod.ts").GiteaRestClient;
  };
  "github": {
    "latest": import("./github/latest/mod.ts").GitHubRestClient;
  };
  "gitlab": {
    "18.11.11": import("./gitlab/18.11.11/mod.ts").GitLabRestClient;
    "19.3.1": import("./gitlab/19.3.1/mod.ts").GitLabRestClient;
  };
};

export type RestClientProvider = keyof RestClientTypeMap;
export type RestClientVersion<TProvider extends RestClientProvider> =
  & keyof RestClientTypeMap[TProvider]
  & string;
