// @generated by codegen/generate-all.ts. DO NOT EDIT.
export const restClientVersions = {
  "azure-devops": ["latest"],
  "bitbucket": ["latest"],
  "codeberg": ["latest"],
  "gitea": ["1.26.4", "1.27.2"],
  "github": ["latest"],
  "gitlab": ["18.11.11", "19.3.1"],
} as const;
