// @generated by codegen/generate-all.ts. DO NOT EDIT.
// OpenAPI source: https://codeberg.org/forgejo/forgejo/raw/tag/v16.0.3/templates/swagger/v1_json.tmpl
// OpenAPI SHA-256: sha256:e37f187d0c054c6330cfaa256d5b34daa32b8b5bfbb4247b741eba096194262f
// Schema license: MIT (https://spdx.org/licenses/MIT.txt)
// Downloaded license SHA-256: sha256:c3b1b78bc8bd3ea13aa4bc9778442d16560270afa235006d816e5e88cef24db4
// Schema license declaration: This file is distributed under the MIT license for the purpose of interoperability (http://opensource.org/licenses/MIT)
// Attribution: Copyright (c) Forgejo contributors
// Full license text and notices: THIRD_PARTY_NOTICES.md
export * from "./ForgejoRestClient.ts";
