/** Stable ordered IDs understood by the Forgejo fluent E2E harness and host CLI. */
export const forgejoFluentContractIds = [
  "core/authentication",
  "core/repositories",
  "core/forks",
  "core/branches",
  "core/tags",
  "core/commits",
  "core/content-reads",
  "core/file-change-commits",
  "core/pull-request-discovery",
  "core/pull-request-mutation",
  "core/pull-request-merge",
  "core/pull-request-reviews-comments",
  "core/commit-statuses",
  "forgejo-extension/file-change-commit",
  "forgejo-extension/pull-request-merge",
  "forgejo-extension/pull-request-review",
  "forgejo-extension/commit-status",
  "shared-capability/current-user-profile",
  "shared-capability/issues",
  "shared-capability/releases",
  "shared-capability/repository-webhooks",
  "shared-capability/ci-run-discovery",
  "shared-capability/packages",
  "shared-capability/blob-reads",
  "shared-capability/pull-request-reviews",
  "shared-capability/branch-rules",
  "shared-capability/unsupported-forgejo-modules",
  "native-access/forgejo/client",
  "native-access/forgejo/entities",
] as const;

export type ForgejoFluentContractId = (typeof forgejoFluentContractIds)[number];
