/** Stable ordered IDs understood by the Gitea fluent E2E harness and host CLI. */
export const giteaFluentContractIds = [
  "core/authentication",
  "core/repositories",
  "core/forks",
  "core/branches",
  "core/tags",
  "core/commits",
  "core/content-reads",
  "core/file-change-commits",
  "core/pull-request-discovery",
  "core/pull-request-mutation",
  "core/pull-request-merge",
  "core/pull-request-reviews-comments",
  "core/commit-statuses",
  "gitea-extension/file-change-commit",
  "gitea-extension/compare-diff-patch",
  "gitea-extension/pull-request-merge",
  "gitea-extension/pull-request-review",
  "gitea-extension/commit-status",
  "shared-capability/current-user-profile",
  "shared-capability/issues",
  "gitea-extension/issue-content-version",
  "shared-capability/releases",
  "shared-capability/repository-webhooks",
  "shared-capability/ci-run-discovery",
  "shared-capability/packages",
  "shared-capability/blob-reads",
  "shared-capability/pull-request-reviews",
  "shared-capability/branch-rules",
  "gitea-extension/branch-rule-priority",
  "shared-capability/unsupported-gitea-modules",
  "native-access/gitea/client",
  "native-access/gitea/entities",
] as const;

export type GiteaFluentContractId = (typeof giteaFluentContractIds)[number];
