/// <reference path="./turndown-plugin-gfm.d.ts" />
// @ts-types="npm:@types/turndown@5.0.6"
import TurndownService from "turndown";

import { tables } from "turndown-plugin-gfm";
import type { LiveTestReportSnapshot } from "./e2e-report-snapshots.ts";

type Endpoint = { id: string; passed: boolean; positive: boolean };

/** Render the raw HTML endpoint table as stable GitHub-flavored Markdown. */
export function renderEndpointTableMarkdown(html: string): string {
  const converter = new TurndownService({
    headingStyle: "atx",
    codeBlockStyle: "fenced",
    bulletListMarker: "-",
  });
  converter.use(tables);
  const escape = converter.escape.bind(converter);
  converter.escape = (text) => escape(text).replaceAll("|", "\\|");
  converter.addRule("reportChrome", {
    filter: (node) =>
      ["HEAD", "TITLE", "STYLE", "SCRIPT", "H1", "P"].includes(node.nodeName) ||
      (node.nodeName === "DIV" && node.getAttribute("class") === "cards"),
    replacement: () => "",
  });
  converter.addRule("operationName", {
    filter: "small",
    replacement: (content) => ` — ${content}`,
  });
  converter.addRule("cellBreak", { filter: "br", replacement: () => "; " });
  converter.addRule("cellError", {
    filter: "pre",
    replacement: (content) => ` — ${content.replace(/\s+/g, " ").trim()}`,
  });
  return converter.turndown(html).trim();
}

/** Render one deterministic human-facing report from validated real-provider evidence. */
export async function renderE2EMarkdownReport(report: LiveTestReportSnapshot): Promise<string> {
  const { gitHost, displayName, version, results, summary } = report;
  const endpoint = JSON.parse(
    await Deno.readTextFile(
      new URL("generated-raw-rest-client-test/endpoint-coverage.json", results),
    ),
  );
  const endpoints: Endpoint[] = endpoint.endpoints;
  if (
    endpoint.gitHost !== gitHost || endpoint.version !== version ||
    endpoint.kind !== "generated-raw-rest-client-test" ||
    !Array.isArray(endpoints) || endpoints.length !== summary.endpoints.operations ||
    endpoints.some((entry) =>
      typeof entry.id !== "string" || typeof entry.passed !== "boolean" ||
      typeof entry.positive !== "boolean"
    ) ||
    new Set(endpoints.map((entry) => entry.id)).size !== endpoints.length ||
    Object.entries(summary.endpoints).some(([key, value]) => endpoint.totals?.[key] !== value) ||
    endpoints.filter((entry) => entry.passed).length !== summary.endpoints.passed ||
    endpoints.filter((entry) => entry.passed && !entry.positive).length !==
      summary.endpoints.negativeOnly
  ) throw new Error(`${gitHost} ${version}: endpoint map and summary disagree`);

  const converted = renderEndpointTableMarkdown(
    await Deno.readTextFile(new URL("generated-raw-rest-client-test/index.html", results)),
  );
  const rows = converted.split("\n").filter((line) => line.startsWith("|"));
  if (rows.length !== summary.endpoints.operations + 2) {
    throw new Error(`${gitHost} ${version}: converted HTML does not contain every endpoint row`);
  }
  const negativeOnly = endpoints.filter((entry) => entry.passed && !entry.positive)
    .map((entry) => entry.id).sort();
  const metrics = summary.sourceCoverage;
  const markdown = [
    "<!-- Generated by `deno task e2e` from real-provider evidence. DO NOT EDIT. -->",
    "",
    `# ${displayName} ${version} — real API E2E`,
    "",
    `> **Provenance:** \`deno task e2e\` ran ${report.run.containerImage} and replaced this report from [its raw evidence](${report.rawEvidenceLink}). No timestamps or runtime log noise are copied into this Markdown.`,
    "",
    "## Generated raw REST client E2E",
    "",
    "| Result | Cases | Endpoints | Positive | Negative-only | Untested |",
    "| :---: | ---: | ---: | ---: | ---: | ---: |",
    `| **${
      summary.suites.generatedRawRestClientTest.passed ? "PASS" : "FAIL"
    }** | ${summary.endpoints.cases} | ${summary.endpoints.passed} / ${summary.endpoints.operations} | ${summary.endpoints.positive} | ${summary.endpoints.negativeOnly} | ${summary.endpoints.missing} |`,
    "",
    ...(summary.handWrittenFluentApiContracts === undefined ? [] : [
      "## Hand-written fluent API E2E",
      "",
      `**${
        summary.suites.handWrittenFluentApiTest?.passed ? "PASS" : "FAIL"
      }** hand-written contracts against the same live Git-host environment:`,
      "",
      ...summary.handWrittenFluentApiContracts.contracts.flatMap((contract) => [
        `### ${contract.name}`,
        "",
        ...contract.assertions.map((assertion) => `- ${assertion}`),
        "",
      ]),
    ]),
    "## Generated client coverage",
    "",
    "Measured by Deno against the generated REST client, not the Git host.",
    "",
    "| Metric | Covered / total | Coverage |",
    "| :--- | ---: | ---: |",
    ...(["lines", "branches", "functions"] as const).map((name) =>
      `| ${name} | ${metrics[name].covered} / ${metrics[name].total} | ${
        metrics[name].percent.toFixed(2)
      }% |`
    ),
    "",
    "## Coverage boundaries",
    "",
    `${summary.endpoints.positive} operations have a passing positive-response case (HTTP 2xx/3xx). ${summary.endpoints.negativeOnly} have negative-only checks: expected errors, with no successful-response test. Endpoint coverage does not prove every successful API behavior or server implementation path.`,
    "",
    ...(negativeOnly.length
      ? negativeOnly.map((id) => `- \`${id.replaceAll("`", "\\`")}\``)
      : ["No negative-only operations."]),
    "",
    "## Endpoint results",
    "",
    "PASS = positive-response coverage; NEGATIVE = expected-error-only coverage; FAIL = a failed or missing check. Responses below came from the real Git-host container.",
    "",
    converted,
    "",
  ].join("\n");
  const child = new Deno.Command(Deno.execPath(), {
    args: ["fmt", "--no-config", "--line-width=100", "--ext=md", "-"],
    stdin: "piped",
    stdout: "piped",
    stderr: "piped",
  }).spawn();
  const writer = child.stdin.getWriter();
  await writer.write(new TextEncoder().encode(markdown));
  await writer.close();
  const output = await child.output();
  if (!output.success) throw new Error(new TextDecoder().decode(output.stderr));
  return new TextDecoder().decode(output.stdout);
}
