// @generated by codegen/generate.ts. DO NOT EDIT.
import type { RestOperation } from "./operation.ts";

type RestStatusDigit = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;

/** Status values exposed by Fetch: opaque status 0 plus HTTP 100 through 599. */
export type RestHttpStatus =
  | 0
  | (
    `${1 | 2 | 3 | 4 | 5}${RestStatusDigit}${RestStatusDigit}` extends
      `${infer TStatus extends number}` ? TStatus : never
  );

/** Fetch status values for which `Response.ok` is true. */
export type RestSuccessfulStatus = `${2}${RestStatusDigit}${RestStatusDigit}` extends
  `${infer TStatus extends number}` ? TStatus
  : never;

/** A response described by the provider's OpenAPI document. */
export type RestResponse<
  TStatus extends number,
  TBody,
  TMediaType extends string | undefined,
  TOk extends boolean,
  THeaderValues extends Readonly<Record<string, string | undefined>> = Readonly<
    Record<string, never>
  >,
> = {
  documented: true;
  ok: TOk;
  status: TStatus;
  mediaType: TMediaType;
  body: TBody;
  headerValues: THeaderValues;
  headers: Headers;
  /** Native response; generated decoding consumes its body, while raw parse modes transfer it. */
  response: Response;
  operation: RestOperation;
};

/** A response status or media type that was absent from the upstream specification. */
export type RestUndocumentedResponse = {
  documented: false;
  ok: boolean;
  status: number;
  mediaType: string | undefined;
  body: unknown;
  headerValues: Readonly<Record<string, string>>;
  headers: Headers;
  response: Response;
  operation: RestOperation;
};

export type AnyRestResponse =
  | RestResponse<
    number,
    unknown,
    string | undefined,
    boolean,
    Readonly<Record<string, string | undefined>>
  >
  | RestUndocumentedResponse;
