// @generated by codegen/generate-all.ts. DO NOT EDIT.
// OpenAPI source: https://raw.githubusercontent.com/go-gitea/gitea/v1.26.4/templates/swagger/v1_json.tmpl
// OpenAPI SHA-256: sha256:0b69d8398ae3557ff8480c55ee3abebd21131ddac39c23621264a69f13cd893d
// Schema license: MIT (https://raw.githubusercontent.com/go-gitea/gitea/v1.26.4/LICENSE)
// Downloaded license SHA-256: sha256:ed2f10a9d78b8c6c9ef33f1420d0eb266981891caf2f15d630553f02dc60d3ae
// Attribution: Copyright (c) 2016 The Gitea Authors; Copyright (c) 2015 The Gogs Authors
// Full license text and notices: THIRD_PARTY_NOTICES.md
export * from "./GiteaRestClient.ts";
