// @generated by codegen/generate.ts. DO NOT EDIT.
import { createClient } from "../../../../packages/pangit/src/api/mod.ts";
import type { GeneratedE2EManifest } from "./e2e-manifest.ts";

const provider = "gitea";
const version = "1.27.2";

type DisposableRepository = { delete(): Promise<void> };

/** Fail one generated fluent-contract assertion with a stable message. */
function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

/** Resolve a manifest fixture reference used by the generated fluent contract. */
function resolve(value: string, manifest: GeneratedE2EManifest): string {
  return value.replace(/\$\{([^}]+)\}/g, (_, name: string) => {
    const resolved = manifest.variables[name];
    assert(resolved !== undefined, `Missing fluent contract fixture ${name}`);
    return String(resolved);
  });
}

/** Exercise the universal repository-container API against the live provider sandbox. */
export async function runRepositoryContainerContract(
  t: Deno.TestContext,
  value: unknown,
): Promise<void> {
  const manifest = value as GeneratedE2EManifest;
  const contract = manifest.repositoryContainerContract;
  assert(contract !== undefined, "Generated suite has no repository-container contract");
  const userName = resolve(contract.user, manifest);
  const userRepositoryName = resolve(contract.userRepository, manifest);
  const organizationName = resolve(contract.organization, manifest);
  const organizationRepositoryName = resolve(contract.organizationRepository, manifest);
  const mutationRepositoryName = resolve(contract.mutationRepository, manifest);
  const renamedRepositoryName = `${mutationRepositoryName}-renamed`;
  const token = (await Deno.readTextFile(
    `${manifest.runner.credentials}/${manifest.credentials.tokenFile}`,
  )).trim();
  const assertions: string[] = [];

  const passed = await t.step("fluent repository-container contract", async () => {
    const connection = createClient(provider, version, manifest.service.apiUrl);
    const git = await connection.auth.token(token);
    assert(git.provider === provider && git.version === version, "Authorization changed selection");
    assertions.push("token authorization retains the selected fluent client");

    const containers = await git.containers();
    assert(
      containers.some((container) => container.kind === "user" && container.name === userName),
      "Container discovery omitted the authenticated user",
    );
    assert(
      containers.some((container) =>
        container.kind === "organization" && container.name === organizationName
      ),
      "Container discovery omitted the sandbox organization",
    );
    assertions.push("container discovery returns user and organization owners");

    const user = await git.container(userName);
    assert(user.kind === "user" && user.name === userName, "User container lookup was incorrect");
    const organization = await git.container(organizationName);
    assert(
      organization.kind === "organization" && organization.name === organizationName,
      "Organization container lookup was incorrect",
    );
    assertions.push("container(name) resolves both user and organization owners");

    assert(
      await user.hasRepository(userRepositoryName),
      "Direct user repository existence check missed the fixture",
    );
    const foundUserRepository = await user.findRepository(userRepositoryName);
    assert(foundUserRepository !== undefined, "Direct optional repository lookup missed the fixture");
    assert(
      foundUserRepository.fullName === `${userName}/${userRepositoryName}`,
      "Direct optional repository lookup returned the wrong entity",
    );
    const userRepository = await user.repository(userRepositoryName);
    assert(
      userRepository.fullName === `${userName}/${userRepositoryName}`,
      "Required user repository lookup returned the wrong entity",
    );
    assertions.push("user repository exists, optional lookup, and required lookup are direct");

    const organizationRepositories = await organization.repositories();
    assert(
      organizationRepositories.some((repository) =>
        repository.name === organizationRepositoryName
      ),
      "Organization repository listing omitted the fixture",
    );
    const organizationRepository = await organization.repository(organizationRepositoryName);
    assert(
      organizationRepository.owner === organizationName,
      "Organization repository lookup returned the wrong owner",
    );
    assertions.push("organization repositories list and fetch through the same container contract");

    const nativeUserName = await user.native.gitea((context) => {
      assert(
        context.client.constructor.name === "GiteaRestClient",
        "Native door returned the wrong client",
      );
      assert(context.kind === "user", "User native door returned the wrong container kind");
      return context.container.login;
    });
    assert(nativeUserName === userName, "User native door returned the wrong generated payload");
    const nativeRepositoryName = await organizationRepository.native.gitea(
      ({ client, repository }) => {
        assert(
          client.constructor.name === "GiteaRestClient",
          "Native door returned the wrong client",
        );
        return repository.full_name;
      },
    );
    assert(
      nativeRepositoryName === `${organizationName}/${organizationRepositoryName}`,
      "Repository native door returned the wrong generated payload",
    );
    assertions.push("container and repository native.gitea retain exact generated contexts");

    let disposable: DisposableRepository | undefined;
    try {
      const created = await user.createRepository(mutationRepositoryName, {
        description: "PanGit fluent contract E2E",
        private: true,
        initialize: true,
        defaultBranch: "main",
      });
      disposable = created;
      assert(
        created.owner === userName && created.name === mutationRepositoryName &&
          created.private === true,
        "User repository creation returned the wrong entity",
      );

      const renamed = await created.rename(renamedRepositoryName);
      disposable = renamed;
      assert(renamed.name === renamedRepositoryName, "Repository rename returned the wrong entity");
      const refreshed = await user.repository(renamedRepositoryName);
      assert(refreshed.id === renamed.id, "Renamed repository could not be fetched");

      await renamed.delete();
      disposable = undefined;
      assertions.push("user repository create, rename, refresh, and delete succeed");
    } finally {
      await disposable?.delete();
    }
  });

  await Deno.writeTextFile(
    `${manifest.runner.results}/repository-container-contract.json`,
    JSON.stringify(
      {
        schemaVersion: 1,
        provider: manifest.provider,
        version: manifest.version,
        kind: "fluent-repository-container",
        passed,
        assertions,
      },
      null,
      2,
    ) + "\n",
  );
  assert(passed, "The fluent repository-container contract failed");
}
