// @generated by codegen/generate.ts. DO NOT EDIT.
import manifest from "./manifest.json" with { type: "json" };

const results = manifest.runner.results;
const raw = `${results}/coverage-raw`;
const target = `${manifest.runner.workspace}/${manifest.clientImplementation}`;
async function command(args: string[]): Promise<Deno.CommandOutput> {
  const result = await new Deno.Command(Deno.execPath(), { args, stdout: "piped", stderr: "piped" }).output();
  const output = new TextDecoder().decode(result.stdout) + new TextDecoder().decode(result.stderr);
  if (args[0] !== "test") console.log(output);
  return result;
}

const test = await command(["test", "--config=deno.json", "--no-lock", `--allow-net=${new URL(manifest.service.apiUrl).host}`, `--allow-read=${manifest.runner.workspace},${manifest.runner.credentials}`, `--allow-write=${results}`, `--coverage=${raw}`, "--clean", "--coverage-raw-data-only", `--junit-path=${results}/junit.xml`, "e2e_test.ts"]);
await Deno.writeFile(`${results}/test.log`, new Uint8Array([...test.stdout, ...test.stderr]));
console.log(`Real E2E process exited ${test.code}; full output: ${results}/test.log`);
let reportingPassed = true;
for (const args of [
  ["coverage", `--include=${target}`, "--lcov", `--output=${results}/coverage.lcov`, raw],
  ["coverage", `--include=${target}`, "--html", raw],
]) {
  const result = await command(args);
  reportingPassed &&= result.success;
}
if (reportingPassed) {
  await Deno.rename(`${raw}/html`, `${results}/coverage`);
  const lcov = (await Deno.readTextFile(`${results}/coverage.lcov`)).replace(/^SF:.*$/gm, `SF:${manifest.clientImplementation}`);
  await Deno.writeTextFile(`${results}/coverage.lcov`, lcov);
  const metric = (found: string, hit: string) => {
    const total = Number(lcov.match(new RegExp(`^${found}:(\\d+)$`, "m"))?.[1]);
    const covered = Number(lcov.match(new RegExp(`^${hit}:(\\d+)$`, "m"))?.[1]);
    return { total, covered, percent: total === 0 ? 100 : Number((100 * covered / total).toFixed(2)) };
  };
  const endpoint = JSON.parse(await Deno.readTextFile(`${results}/endpoint-coverage.json`));
  await Deno.writeTextFile(`${results}/summary.json`, JSON.stringify({ provider: manifest.provider, version: manifest.version, kind: "real-http-e2e", passed: test.success, endpoints: endpoint.totals, sourceCoverage: { lines: metric("LF", "LH"), branches: metric("BRF", "BRH"), functions: metric("FNF", "FNH") } }, null, 2) + "\n");
  for await (const entry of Deno.readDir(`${results}/coverage`)) {
    if (!entry.name.endsWith(".html")) continue;
    const path = `${results}/coverage/${entry.name}`;
    await Deno.writeTextFile(path, (await Deno.readTextFile(path)).replace(/^(\s*)at (?:Mon|Tue|Wed|Thu|Fri|Sat|Sun), .*$/m, "$1from the real E2E run"));
  }
}
await Deno.remove(raw, { recursive: true }).catch(() => {});
Deno.exit(test.success && reportingPassed ? 0 : 1);
