// @generated by codegen/generate.ts. DO NOT EDIT.
import { RestClient, type RestClientOptions, type RestOperationInput, type AnyRestResponse } from "../../../../packages/pangit/src/providers/runtime/mod.ts";
import type { E2EStep, GeneratedE2EManifest } from "./e2e-manifest.ts";

type Client = { rest: RestClient };
type Constructor = new (options: RestClientOptions | RestClient) => Client;
type RecordValue = Record<string, unknown>;
type CaseResult = { operationId: string; scenario: string; name: string; expected: number[]; status?: number; url?: string; method?: string; passed: boolean; error?: string; attempts: number[]; note?: string };

function get(value: unknown, path: string): unknown {
  return path.split(".").reduce((current, key) => (current as RecordValue | undefined)?.[key], value);
}

function json(value: unknown): string {
  return JSON.stringify(value, (_, item) => typeof item === "bigint" ? (Number.isSafeInteger(Number(item)) ? Number(item) : item.toString()) : item);
}

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

function escape(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}

export async function runSuite(t: Deno.TestContext, value: unknown, ClientType: Constructor): Promise<void> {
  const manifest = value as GeneratedE2EManifest;
  const vars: RecordValue = { ...manifest.variables, version: manifest.version, username: manifest.credentials.username, password: manifest.credentials.password, apiUrl: manifest.service.apiUrl };
  const token = (await Deno.readTextFile(`${manifest.runner.credentials}/${manifest.credentials.tokenFile}`)).trim();
  assert(token.length > 0, "Sandbox did not issue an API token");
  const credentials = {
    token: { [manifest.credentials.authorizationHeader]: manifest.credentials.tokenPrefix + token },
    basic: { [manifest.credentials.authorizationHeader]: `Basic ${btoa(`${manifest.credentials.username}:${manifest.credentials.password}`)}` },
    none: {},
  };
  let observed: { url: string; method: string } | undefined;
  const options = (auth: keyof typeof credentials): RestClientOptions => ({
    baseUrl: manifest.service.apiUrl,
    headers: credentials[auth],
    useOperationServers: false,
    beforeRequest: (request) => {
      assert(new URL(request.url).origin === new URL(manifest.service.apiUrl).origin, "E2E request escaped its sandbox");
      observed = { url: request.url, method: request.method };
      return request;
    },
  });
  // Both construction modes make real network requests; neither injects or replaces fetch.
  const clients = { token: new ClientType(options("token")), basic: new ClientType(new RestClient(options("basic"))), none: new ClientType(options("none")) };
  const operations = new Map(manifest.operations.map((operation) => [operation.id, operation]));
  const records: CaseResult[] = [];

  async function interpolate(input: unknown): Promise<unknown> {
    if (typeof input === "string") {
      const exact = input.match(/^\$\{([^}]+)\}$/);
      if (exact) {
        const result = get(vars, exact[1]);
        assert(result !== undefined, `Missing scenario fixture ${exact[1]}`);
        return result;
      }
      return input.replace(/\$\{([^}]+)\}/g, (_, name) => {
        const result = get(vars, name);
        assert(result !== undefined, `Missing scenario fixture ${name}`);
        return String(result);
      });
    }
    if (Array.isArray(input)) return await Promise.all(input.map(interpolate));
    if (input && typeof input === "object") {
      const object = input as RecordValue;
      if (Array.isArray(object.$bytes)) return new Uint8Array(object.$bytes as number[]);
      if (typeof object.$file === "string") return (await Deno.readTextFile(`${manifest.runner.credentials}/${object.$file}`)).trim();
      if (object.$base64 !== undefined) return btoa(String(await interpolate(object.$base64)));
      if (object.$basic !== undefined) return `Basic ${btoa(String(await interpolate(object.$basic)))}`;
      const result: RecordValue = {};
      for (const [key, item] of Object.entries(object)) result[key] = await interpolate(item);
      return result;
    }
    return input;
  }

  async function execute(scenario: string, step: E2EStep): Promise<void> {
    const operation = operations.get(step.operationId)!;
    const record: CaseResult = { operationId: step.operationId, scenario, name: step.name ?? step.operationId, expected: step.expect.status, passed: false, attempts: [], note: step.note };
    records.push(record);
    observed = undefined;
    try {
      const input = await interpolate(step.input ?? {}) as RestOperationInput;
      const client = clients[step.auth ?? "token"] as unknown as Record<string, (input: RestOperationInput, options: { signal: AbortSignal; redirect: "manual" }) => Promise<AnyRestResponse>>;
      const deadline = Date.now() + (step.poll?.timeoutMs ?? 0);
      let result: AnyRestResponse;
      let consecutiveSuccesses = 0;
      while (true) {
      if (step.fixture) {
        const url = String(await interpolate(step.fixture.url));
        assert(new URL(url).origin === new URL(manifest.service.apiUrl).origin, "Fixture request escaped its sandbox");
        observed = {url, method: step.fixture.method};
        const response = await fetch(url, {method: step.fixture.method, headers: {...credentials[step.auth ?? "token"], "Content-Type": "application/json"}, body: step.fixture.json === undefined ? undefined : json(await interpolate(step.fixture.json)), signal: AbortSignal.timeout(manifest.runner.timeoutMs), redirect: "manual"});
        const content = await response.text();
        result = { status: response.status, body: content ? JSON.parse(content) : undefined } as AnyRestResponse;
      } else {
        result = await client[operation.methodName](input, { signal: AbortSignal.timeout(manifest.runner.timeoutMs), redirect: "manual" });
      }
      record.attempts.push(result.status);
      record.status = result.status;
      Object.assign(record, observed);
      assert(observed !== undefined, "Client did not issue an HTTP request");
      try {
      assert(step.expect.status.includes(result.status), `Expected HTTP ${step.expect.status.join("/")}, got ${result.status}: ${json(result.body)}`);
      for (const [path, expected] of Object.entries(step.expect.equals ?? {})) {
        const wanted = await interpolate(expected);
        assert(json(get(result, path)) === json(wanted), `${path}: expected ${json(wanted)}, got ${json(get(result, path))}`);
      }
      for (const [path, expected] of Object.entries(step.expect.contains ?? {})) {
        const actual = get(result, path);
        const wanted = await interpolate(expected);
        assert(typeof actual === "string" ? actual.includes(String(wanted)) : Array.isArray(actual) && actual.some((item) => json(item) === json(wanted)), `${path} did not contain expected value`);
      }
      for (const path of step.expect.nonempty ?? []) {
        const actual = get(result, path);
        assert(actual !== undefined && actual !== null && actual !== "" && (!Array.isArray(actual) || actual.length > 0), `${path} was empty`);
      }
      consecutiveSuccesses++;
      if (consecutiveSuccesses >= (step.poll?.consecutiveSuccesses ?? 1)) break;
      assert(Date.now() < deadline, "Readiness did not stabilize before timeout");
      await new Promise((resolve) => setTimeout(resolve, step.poll!.intervalMs));
      } catch (error) {
        consecutiveSuccesses = 0;
        if (!step.poll || Date.now() >= deadline || (!step.expect.status.includes(result.status) && !step.poll.retryStatuses.includes(result.status))) throw error;
        await new Promise((resolve) => setTimeout(resolve, step.poll!.intervalMs));
      }
      }
      for (const [name, path] of Object.entries(step.capture ?? {})) {
        const captured = get(result, path);
        assert(captured !== undefined, `Missing response fixture ${path}`);
        vars[name] = captured;
      }
      record.passed = true;
    } catch (error) {
      Object.assign(record, observed);
      record.error = (error instanceof Error ? error.message : String(error)).replaceAll(token, "[redacted]").replaceAll(manifest.credentials.password, "[redacted]");
      throw new Error(record.error);
    }
  }

  try {
    for (const scenario of manifest.scenarios) {
      for (const step of scenario.steps) await t.step(`${scenario.name}: ${step.name ?? step.operationId}`, () => execute(scenario.name, step));
    }
    for (const step of manifest.negativeCases) await t.step(`negative: ${step.name ?? step.operationId}`, () => execute("negative contract", step));
  } finally {
    const endpoints = manifest.operations.map((operation) => {
      const cases = records.filter((record) => record.operationId === operation.id);
      return { ...operation, passed: cases.length > 0 && cases.every((item) => item.passed), positive: cases.some((item) => item.passed && item.status! >= 200 && item.status! < 400), cases };
    });
    const totals = { operations: endpoints.length, passed: endpoints.filter((item) => item.passed).length, positive: endpoints.filter((item) => item.passed && item.positive).length, negativeOnly: endpoints.filter((item) => item.passed && !item.positive).length, missing: endpoints.filter((item) => item.cases.length === 0).length, failedCases: records.filter((item) => !item.passed).length, cases: records.length, requests: records.reduce((sum, record) => sum + record.attempts.length, 0) };
    const fixtures = records.filter((record) => !operations.has(record.operationId));
    const report = { schemaVersion: 1, provider: manifest.provider, version: manifest.version, image: manifest.image, kind: "real-http-e2e", totals, endpoints, fixtures };
    await Deno.writeTextFile(`${manifest.runner.results}/endpoint-coverage.json`, JSON.stringify(report, null, 2) + "\n");
    const rows = endpoints.map((endpoint) => `<tr><td class="${endpoint.passed ? "pass" : "fail"}">${endpoint.passed ? endpoint.positive ? "PASS" : "NEGATIVE" : "FAIL"}</td><td>${escape(endpoint.method)} ${escape(endpoint.path)}<small>${escape(endpoint.id)}</small></td><td>${endpoint.cases.map((item) => `${item.status ?? "no response"}: ${escape(item.name)}${item.error ? `<pre>${escape(item.error)}</pre>` : ""}`).join("<br>")}</td></tr>`).join("\n");
    const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(manifest.provider)} ${escape(manifest.version)} real API E2E</title><style>body{font-family:system-ui;background:#0d1117;color:#e6edf3;margin:32px}h1{margin-bottom:8px}p,small{color:#8b949e}a{color:#58a6ff}table{border-collapse:collapse;width:100%;margin-top:24px}th,td{border-bottom:1px solid #30363d;text-align:left;padding:12px;vertical-align:top}.pass{color:#3fb950}.fail{color:#f85149}small{display:block}pre{white-space:pre-wrap;max-width:700px}.cards{display:flex;gap:30px;background:#161b22;border-radius:12px;padding:24px}strong{display:block;font-size:28px}</style></head><body><h1>${escape(manifest.provider)} ${escape(manifest.version)} — real API E2E</h1><p>Requests executed by the generated client against ${escape(manifest.service.apiUrl)} in Compose. No mocked transport.</p><div class="cards"><div><strong>${totals.passed}/${totals.operations}</strong>Endpoints passed</div><div><strong>${totals.positive}</strong>Positive-response coverage</div><div><strong>${totals.negativeOnly}</strong>Negative-only coverage</div><div><strong>${totals.failedCases}</strong>Failed cases</div></div><p><a href="coverage/index.html">Client source coverage</a> · <a href="endpoint-coverage.json">Endpoint map</a> · <a href="coverage.lcov">LCOV</a> · <a href="junit.xml">JUnit</a> · <a href="test.log">Test output</a></p><table><thead><tr><th>Result</th><th>Endpoint</th><th>Real responses and assertions</th></tr></thead><tbody>${rows}</tbody></table></body></html>`;
    await Deno.writeTextFile(`${manifest.runner.results}/index.html`, html);
  }
  assert(records.every((record) => record.passed), "One or more real endpoint assertions failed");
  assert(manifest.operations.every((operation) => records.some((record) => record.operationId === operation.id && record.passed)), "Not every operation passed a real HTTP E2E case");
}
