const warning = "@generated by codegen/generate.ts. DO NOT EDIT.";

export function generatedComment(style: "//" | "#" | "<!--"): string {
  return style === "<!--" ? `<!-- ${warning} -->\n` : `${style} ${warning}\n`;
}

/** Shell scripts must keep their interpreter directive on the first line. */
export function markGenerated(content: string, style: "//" | "#" | "<!--"): string {
  const comment = generatedComment(style);
  if (content.startsWith("#!")) {
    const newline = content.indexOf("\n");
    return newline < 0
      ? `${content}\n${comment}`
      : `${content.slice(0, newline + 1)}${comment}${content.slice(newline + 1)}`;
  }
  return `${comment}${content}`;
}
