// @generated by codegen/generate-all.ts. DO NOT EDIT.
// OpenAPI source: https://raw.githubusercontent.com/github/rest-api-description/085fb86b030e75ae7ba65a2523f8729fdcae19d4/descriptions/api.github.com/api.github.com.yaml
// OpenAPI SHA-256: sha256:0ca05b6840052d8d1971523a6c243e36765e2264c797fc56a8f7b5e04ce4a147
// Schema license: MIT (https://raw.githubusercontent.com/github/rest-api-description/085fb86b030e75ae7ba65a2523f8729fdcae19d4/LICENSE.md)
// Downloaded license SHA-256: sha256:3243761cbac07e6d169a5a2f4e7c25cc544da85248e735df74c3672e055cc87b
// Attribution: Copyright (c) 2020 GitHub
// Full license text and notices: THIRD_PARTY_NOTICES.md
export * from "./GitHubRestClient.ts";
