// @generated by codegen/generate-all.ts. DO NOT EDIT.
// OpenAPI source: https://raw.githubusercontent.com/MicrosoftDocs/vsts-rest-api-specs/master/specification/git/7.2/git.json
// OpenAPI SHA-256: sha256:7e7b5bd1af4b486a1af498c78150ca1083b7c6d621671bde26967406e3d75d6d
// Schema license: no separate license evidence recorded
// Third-party source notice: THIRD_PARTY_NOTICES.md
export * from "./AzureDevOpsRestClient.ts";
