// @generated by codegen/generate-all.ts. DO NOT EDIT.
// OpenAPI source: https://raw.githubusercontent.com/go-gitea/gitea/v1.27.2/templates/swagger/v1_openapi3_json.tmpl
// OpenAPI SHA-256: sha256:0f5a90ebce4a7efff9e338a8944894283c14757d759b28fab4940c461cf2f120
// Schema license: MIT (https://raw.githubusercontent.com/go-gitea/gitea/v1.27.2/LICENSE)
// Downloaded license SHA-256: sha256:ed2f10a9d78b8c6c9ef33f1420d0eb266981891caf2f15d630553f02dc60d3ae
// Attribution: Copyright (c) 2016 The Gitea Authors; Copyright (c) 2015 The Gogs Authors
// Full license text and notices: THIRD_PARTY_NOTICES.md
export * from "./GiteaRestClient.ts";
