// @generated by codegen/generate-all.ts. DO NOT EDIT.
// OpenAPI source: https://gitlab.com/gitlab-org/gitlab/-/raw/v19.3.1-ee/doc/api/openapi/openapi_v2.yaml
// OpenAPI SHA-256: sha256:17a1d86d6d6da7255f71ad9828c4378a16e48b505f0959896cc0f23e9fd5ee17
// Schema license: no separate license evidence recorded
// Third-party source notice: THIRD_PARTY_NOTICES.md
export * from "./GitLabRestClient.ts";
