// @generated by codegen/generate.ts. DO NOT EDIT.
import type { RestClientOptions } from "./runtime/mod.ts";
import type { Provider, ProviderSelection, ProviderVersion } from "./provider.ts";

export type ClientOptions = Omit<RestClientOptions, "headers">;

export type AuthorizedClient<
  TProvider extends Provider,
  TVersion extends ProviderVersion<TProvider>,
> = ProviderSelection<TProvider, TVersion>;
