// @generated by codegen/generate.ts. DO NOT EDIT.
import type { RestClientProvider, RestClientVersion } from "./clients.ts";

export type Provider = RestClientProvider;
export type ProviderVersion<TProvider extends Provider> = RestClientVersion<TProvider>;

export interface ProviderSelection<
  TProvider extends Provider,
  TVersion extends ProviderVersion<TProvider>,
> {
  readonly provider: TProvider;
  readonly version: TVersion;
}
