// @generated by codegen/generate.ts. DO NOT EDIT.
import type { RestClientProvider, RestClientTypeMap, RestClientVersion } from "./clients.ts";
import type { RestClient, RestClientOptions } from "./runtime/mod.ts";

type RestClientLoader = (
  options: RestClientOptions | RestClient,
) => Promise<unknown>;

const restClientLoaders = {
  "azure-devops": {
    "latest": async (options) =>
      new (await import("./azure-devops/latest/mod.ts")).AzureDevOpsRestClient(options),
  },
  "bitbucket": {
    "latest": async (options) =>
      new (await import("./bitbucket/latest/mod.ts")).BitbucketRestClient(options),
  },
  "codeberg": {
    "latest": async (options) =>
      new (await import("./codeberg/latest/mod.ts")).CodebergRestClient(options),
  },
  "gitea": {
    "1.26.4": async (options) =>
      new (await import("./gitea/1.26.4/mod.ts")).GiteaRestClient(options),
    "1.27.2": async (options) =>
      new (await import("./gitea/1.27.2/mod.ts")).GiteaRestClient(options),
  },
  "github": {
    "latest": async (options) =>
      new (await import("./github/latest/mod.ts")).GitHubRestClient(options),
  },
  "gitlab": {
    "18.11.11": async (options) =>
      new (await import("./gitlab/18.11.11/mod.ts")).GitLabRestClient(options),
    "19.3.1": async (options) =>
      new (await import("./gitlab/19.3.1/mod.ts")).GitLabRestClient(options),
  },
} satisfies Record<RestClientProvider, Record<string, RestClientLoader>>;

export function loadRestClient<
  TProvider extends RestClientProvider,
  TVersion extends RestClientVersion<TProvider>,
>(
  provider: TProvider,
  version: TVersion,
  options: RestClientOptions | RestClient,
): Promise<RestClientTypeMap[TProvider][TVersion]> {
  const loader = (restClientLoaders[provider] as Record<string, RestClientLoader>)[version];
  if (loader === undefined) {
    throw new Error(`Unknown REST client version ${provider} ${version}`);
  }
  return loader(options) as Promise<RestClientTypeMap[TProvider][TVersion]>;
}
