/** Stable independently selectable GitLab fluent contract IDs. */
export const gitlabFluentContractIds = [
  "core/authentication",
  "core/oauth",
  "gitlab-extension/operations",
  "core/repositories",
  "core/forks",
  "core/branches",
  "core/tags",
  "core/commits",
  "core/commit-files-pagination",
  "core/content-reads",
  "core/file-changes",
  "core/links",
  "core/pull-requests",
  "core/pull-request-merge",
  "core/pull-request-comments",
  "core/pull-request-approval",
  "core/commit-statuses",
  "shared-capability/issues",
  "shared-capability/releases",
  "shared-capability/packages",
  "shared-capability/branch-rules",
  "shared-capability/branch-protection-enforcement",
  "shared-capability/webhooks",
  "shared-capability/ci-run-discovery",
  "shared-capability/blob-reads",
  "shared-capability/unsupported-modules",
] as const;
