// @generated by codegen/generate-all.ts. DO NOT EDIT.
/** Cancellation and ownership of current, replaced, returned, and late Fetch bodies. */
import type { MaybePromise } from "./contracts/request.ts";

export function bindResponseStream(
  body: ReadableStream<Uint8Array> | null,
  signal: AbortSignal | undefined,
): ReadableStream<Uint8Array> | null {
  if (body === null || signal === undefined) return body;
  const reader = body.getReader();
  let finished = false;
  const cleanup = (): void => signal.removeEventListener("abort", onAbort);
  const release = (): void => {
    try {
      reader.releaseLock();
    } catch {
      // A pending read retains the lock until cancellation settles.
    }
  };
  let controller: ReadableStreamDefaultController<Uint8Array> | undefined;
  const onAbort = (): void => {
    if (finished) return;
    finished = true;
    cleanup();
    controller?.error(signal.reason);
    void reader.cancel(signal.reason).finally(release).catch(() => undefined);
  };

  return new ReadableStream<Uint8Array>({
    start(streamController) {
      controller = streamController;
      signal.addEventListener("abort", onAbort, { once: true });
      if (signal.aborted) onAbort();
    },
    async pull(streamController) {
      if (finished) return;
      try {
        const chunk = await reader.read();
        if (finished) return;
        if (signal.aborted) {
          onAbort();
        } else if (chunk.done) {
          finished = true;
          cleanup();
          release();
          streamController.close();
        } else {
          streamController.enqueue(chunk.value);
        }
      } catch (error) {
        if (finished) return;
        finished = true;
        cleanup();
        release();
        streamController.error(signal.aborted ? signal.reason : error);
      }
    },
    async cancel(reason) {
      if (finished) return;
      finished = true;
      cleanup();
      try {
        await reader.cancel(reason);
      } finally {
        release();
      }
    },
  }, { highWaterMark: 0 });
}

export function bindResponseToSignal(
  response: Response,
  signal: AbortSignal | undefined,
): Response {
  if (response.body === null || signal === undefined) return response;
  const bound = new Response(bindResponseStream(response.body, signal), {
    headers: response.headers,
    status: response.status,
    statusText: response.statusText,
  });
  for (
    const [name, value] of [
      ["redirected", response.redirected],
      ["type", response.type],
      ["url", response.url],
    ] as const
  ) {
    try {
      Object.defineProperty(bound, name, { configurable: true, value });
    } catch {
      // Some runtimes may not permit shadowing native response metadata.
    }
  }
  return bound;
}

export async function readResponseBytes(
  body: ReadableStream<Uint8Array> | null,
  signal: AbortSignal | undefined,
): Promise<Uint8Array<ArrayBuffer>> {
  if (body === null) return new Uint8Array();
  const reader = body.getReader();
  const chunks: Uint8Array[] = [];
  let length = 0;
  let cancellation: Promise<void> | undefined;
  const release = (): void => {
    try {
      reader.releaseLock();
    } catch {
      // Pending cancellation retains the lock until its promise settles.
    }
  };
  const cancel = (reason: unknown): void => {
    cancellation ??= reader.cancel(reason).catch(() => undefined);
  };
  const onAbort = (): void => {
    cancel(signal?.reason);
  };
  signal?.addEventListener("abort", onAbort, { once: true });
  try {
    while (true) {
      throwIfAborted(signal);
      const chunk = await reader.read();
      throwIfAborted(signal);
      if (chunk.done) break;
      chunks.push(chunk.value);
      length += chunk.value.byteLength;
    }
  } catch (error) {
    cancel(signal?.aborted ? signal.reason : error);
    throwIfAborted(signal);
    throw error;
  } finally {
    signal?.removeEventListener("abort", onAbort);
    if (cancellation === undefined) release();
    else void cancellation.then(release);
  }
  const bytes = new Uint8Array(length);
  let offset = 0;
  for (const chunk of chunks) {
    bytes.set(chunk, offset);
    offset += chunk.byteLength;
  }
  return bytes;
}

export function throwIfAborted(signal: AbortSignal | undefined): void {
  signal?.throwIfAborted();
}

export function preserveRequestCancellation(
  request: Request,
  signal: AbortSignal | undefined,
): Request {
  if (signal === undefined) return request;
  return new Request(request, {
    signal: AbortSignal.any([signal, request.signal]),
  });
}

export async function runBeforeRequestHook(
  currentRequest: Request,
  callback: () => MaybePromise<Request>,
  signal: AbortSignal | undefined,
): Promise<Request> {
  return await runReplacementHookWithSignal(
    currentRequest,
    callback,
    signal,
    cancelRequestBody,
    () => new Error("Request body discarded after beforeRequest returned a replacement"),
  );
}

export async function runFetchWithSignal(
  request: Request,
  callback: () => MaybePromise<Response>,
  signal: AbortSignal | undefined,
): Promise<Response> {
  if (signal?.aborted) {
    cancelRequestBody(request, signal.reason);
    throw signal.reason;
  }
  const pending = Promise.resolve().then(callback);
  if (signal === undefined) {
    try {
      return await pending;
    } catch (error) {
      cancelRequestBody(request, error);
      throw error;
    }
  }

  return await new Promise<Response>((resolve, reject) => {
    let aborted = false;
    let settled = false;
    const cleanup = (): void => signal.removeEventListener("abort", onAbort);
    const onAbort = (): void => {
      if (settled) return;
      aborted = true;
      settled = true;
      cleanup();
      cancelRequestBody(request, signal.reason);
      reject(signal.reason);
    };
    signal.addEventListener("abort", onAbort, { once: true });
    if (signal.aborted) onAbort();
    pending.then(
      (response) => {
        if (settled) {
          if (aborted) cancelResponseBody(response, signal.reason);
          return;
        }
        settled = true;
        cleanup();
        resolve(response);
      },
      (error) => {
        if (settled) return;
        settled = true;
        cleanup();
        cancelRequestBody(request, error);
        reject(error);
      },
    );
  });
}

export async function runAfterResponseHook(
  currentResponse: Response,
  callback: () => MaybePromise<Response>,
  signal: AbortSignal | undefined,
): Promise<Response> {
  return await runReplacementHookWithSignal(
    currentResponse,
    callback,
    signal,
    cancelResponseBody,
    () => new Error("Response body discarded after afterResponse returned a replacement"),
  );
}

async function runReplacementHookWithSignal<TValue extends object>(
  currentValue: TValue,
  callback: () => MaybePromise<TValue>,
  signal: AbortSignal | undefined,
  cancel: (value: TValue, reason: unknown) => void,
  replacementReason: () => unknown,
): Promise<TValue> {
  if (signal === undefined) {
    try {
      const replacement = await callback();
      if (replacement !== currentValue) cancel(currentValue, replacementReason());
      return replacement;
    } catch (error) {
      cancel(currentValue, error);
      throw error;
    }
  }
  if (signal.aborted) {
    cancel(currentValue, signal.reason);
    throw signal.reason;
  }

  const pending = Promise.resolve().then(callback);
  return await new Promise<TValue>((resolve, reject) => {
    let aborted = false;
    let settled = false;
    const cleanup = (): void => signal.removeEventListener("abort", onAbort);
    const onAbort = (): void => {
      if (settled) return;
      aborted = true;
      settled = true;
      cleanup();
      cancel(currentValue, signal.reason);
      reject(signal.reason);
    };
    signal.addEventListener("abort", onAbort, { once: true });
    if (signal.aborted) onAbort();
    pending.then(
      (replacement) => {
        if (settled) {
          if (aborted && replacement !== currentValue) cancel(replacement, signal.reason);
          return;
        }
        settled = true;
        cleanup();
        if (replacement !== currentValue) cancel(currentValue, replacementReason());
        resolve(replacement);
      },
      (error) => {
        if (settled) return;
        settled = true;
        cleanup();
        cancel(currentValue, error);
        reject(error);
      },
    );
  });
}

function cancelResponseBody(response: Response, reason: unknown): void {
  if (response.body === null) return;
  void response.body.cancel(reason).catch(() => undefined);
}

export function cancelRequestBody(request: Request, reason: unknown): void {
  if (request.body === null) return;
  void request.body.cancel(reason).catch(() => undefined);
}

export async function runWithSignal<T>(
  callback: () => MaybePromise<T>,
  signal: AbortSignal | undefined,
): Promise<T> {
  throwIfAborted(signal);
  const value = Promise.resolve().then(callback);
  if (signal === undefined) return await value;

  return await new Promise<T>((resolve, reject) => {
    let settled = false;
    const settle = (callback: (value: T | PromiseLike<T>) => void, result: T): void => {
      if (settled) return;
      settled = true;
      signal.removeEventListener("abort", onAbort);
      callback(result);
    };
    const fail = (error: unknown): void => {
      if (settled) return;
      settled = true;
      signal.removeEventListener("abort", onAbort);
      reject(error);
    };
    const onAbort = (): void => fail(signal.reason);

    signal.addEventListener("abort", onAbort, { once: true });
    value.then((result) => settle(resolve, result), fail);
  });
}
