// @generated by codegen/generate-all.ts. DO NOT EDIT.
/** Media-type essence classification shared by request and response encoding. */
export function isJson(mediaType: string): boolean {
  const essence = mediaTypeEssence(mediaType);
  return essence === "application/json" || essence.endsWith("+json") ||
    essence.includes("json");
}

export function isMultipart(mediaType: string): boolean {
  return mediaTypeEssence(mediaType).startsWith("multipart/");
}

export function mediaTypeEssence(mediaType: string): string {
  return mediaType.split(";", 1)[0]?.trim().toLowerCase() ?? "";
}
