// @generated by codegen/generate.ts. DO NOT EDIT.
/**
 * Generated native-Fetch runtime for PanGit REST clients.
 *
 * Generated provider clients use this transport to preserve provider-native requests and
 * responses. PanGit exposes provider-native clients without exposing this transport implementation,
 * which remains inside the self-contained generated provider tree.
 *
 * @module
 */

export {
  deepFreezeRestMetadata,
  deepFreezeRestOperations,
  RestClient,
  RestTransportError,
} from "./rest-client.ts";
export {
  isRestDocumentedSuccess,
  isRestSuccess,
  RestApiError,
  RestParseError,
  RestUndocumentedResponseError,
  unwrapRestResponse,
} from "./response.ts";

export type {
  AnyRestResponse,
  RestBinary,
  RestBody,
  RestClientOptions,
  RestGeneratedDecodeMode,
  RestGeneratedRequestOptions,
  RestHeadersProvider,
  RestHttpStatus,
  RestInt64,
  RestJsonData,
  RestJsonNumber,
  RestJsonValue,
  RestMethod,
  RestOperation,
  RestOperationInput,
  RestOperationResponse,
  RestParseMode,
  RestPathGroup,
  RestPathParameter,
  RestQueryParameter,
  RestRequestContext,
  RestRequestOperation,
  RestRequestOptions,
  RestRequestValue,
  RestResponse,
  RestSecurityRequirement,
  RestSuccessfulStatus,
  RestUndocumentedResponse,
} from "./contracts/mod.ts";
export type { RestDocumentedSuccess, RestDocumentedSuccessBody } from "./response.ts";
