// @generated by codegen/generate-all.ts. DO NOT EDIT.
// OpenAPI source: https://codeberg.org/swagger.v1.json
// OpenAPI SHA-256: sha256:bb988ce779fbd7c332391d5abd93b0e6080e12a233945a756aa85093759ad56a
// Schema license: MIT (https://spdx.org/licenses/MIT.txt)
// Downloaded license SHA-256: sha256:c3b1b78bc8bd3ea13aa4bc9778442d16560270afa235006d816e5e88cef24db4
// Schema license declaration: This file is distributed under the MIT license for the purpose of interoperability (http://opensource.org/licenses/MIT)
// Attribution: Copyright (c) Forgejo contributors
// Full license text and notices: THIRD_PARTY_NOTICES.md
export * from "./CodebergRestClient.ts";
