import {
  assertExpectedProviderSet,
  expectedRestClientProviders,
  renderProviderClient,
  replaceGeneratedDirectory,
} from "./generate.ts";
import type { RestClientSpecManifest } from "./client-manifests.ts";
import { extractExportedTypeAliases } from "./generated_type_oracle.ts";
import { parseOpenApiDocument } from "./openapi.ts";
import { renderGeneratedModule } from "./render.ts";

Deno.test("complete provider set is always required", () => {
  assertExpectedProviderSet(expectedRestClientProviders);
  assertThrows(
    () => assertExpectedProviderSet(expectedRestClientProviders.slice(1)),
    "missing=[azure-devops]",
  );
  assertThrows(
    () => assertExpectedProviderSet([...expectedRestClientProviders, "unexpected"]),
    "unexpected=[unexpected]",
  );
});

Deno.test("provider rendering is deterministic and emits one registry entry and method per operation", () => {
  const first = fixtureDocument({
    "/z/{id}": operation("zGet", {
      parameters: [{ in: "path", name: "id", required: true, schema: { type: "string" } }],
    }),
    "/a": operation("aGet"),
  });
  const second = fixtureDocument({
    "/a": operation("aGet"),
    "/z/{id}": operation("zGet", {
      parameters: [{ schema: { type: "string" }, required: true, name: "id", in: "path" }],
    }),
  });

  const rendered = renderProviderClient("fixture", first);
  assert(
    rendered.startsWith("// @generated by codegen/generate.ts. DO NOT EDIT."),
    "Missing first-line generated warning",
  );
  assertEquals(rendered, renderProviderClient("fixture", second));
  for (const method of ["aGet", "zGet"]) {
    assertEquals(count(rendered, `\n  ${method}: {`), 1);
    assertEquals(count(rendered, `\n  ${method}(`), 1);
    assertEquals(count(rendered, `fixtureOperations.${method}, input, options`), 1);
  }
});

Deno.test("generated module ships raw clients behind literal dynamic imports", () => {
  const manifest = {
    schemaVersion: 1,
    providers: {
      gitea: {
        selected: "1.27.2",
        client: {
          className: "GiteaRestClient",
          displayName: "Gitea",
          namespaceName: "GiteaApi",
          variablePrefix: "gitea",
        },
        versions: {
          "1.27.2": {
            destination: "packages/pangit/src/generated/gitea/1.27.2",
            artifacts: {
              client: "src/generated/gitea/1.27.2/client.ts",
              normalized: "codegen/specs/normalized/gitea/1.27.2.json",
              tests: "src/generated/gitea/1.27.2/tests",
            },
          },
        },
      },
    },
  } satisfies RestClientSpecManifest;

  const source = renderGeneratedModule(manifest, {
    restModulePath: "../rest/mod.ts",
  });
  assert(
    source.includes('import type { RestClient, RestClientOptions } from "../rest/mod.ts"'),
    "generated registry must import only transport types",
  );
  assert(
    source.includes('await import("./gitea/1.27.2/client.ts")'),
    "selected raw client must be loaded through a literal dynamic import",
  );
  assertEquals(count(source, 'from "./gitea/1.27.2/client.ts"'), 0);
  assertEquals(count(source, "import { GiteaRestClient }"), 0);
});

Deno.test("unsupported parameter and response constructs fail instead of disappearing", () => {
  assertThrows(
    () =>
      renderProviderClient(
        "fixture",
        fixtureDocument({
          "/cookie": operation("cookieGet", {
            parameters: [{ in: "cookie", name: "session", schema: { type: "string" } }],
          }),
        }),
      ),
    "unsupported cookie location",
  );
  assertThrows(
    () =>
      renderProviderClient(
        "fixture",
        fixtureDocument({
          "/wildcard": {
            get: {
              operationId: "wildcardGet",
              responses: { "2XX": { description: "unsupported wildcard" } },
            },
          },
        }),
      ),
    "Unsupported response status 2XX",
  );
  assertThrows(
    () =>
      renderProviderClient(
        "fixture",
        fixtureDocument({
          "/trace": {
            trace: { operationId: "traceFixture", responses: { "204": { description: "ok" } } },
          },
        }),
      ),
    ".trace is unsupported",
  );
  assertThrows(
    () =>
      renderProviderClient(
        "fixture",
        fixtureDocument({
          "/collections/{parts}": operation("collectionGet", {
            parameters: [{
              in: "path",
              name: "parts",
              required: true,
              schema: { type: "array", items: { type: "string" } },
            }],
          }),
        }),
      ),
    "unsupported path collection schema",
  );
  assertThrows(
    () =>
      renderProviderClient(
        "fixture",
        fixtureDocument({
          "/duplicate": operation("duplicateGet", {
            parameters: [
              { in: "query", name: "page", schema: { type: "integer" } },
              { in: "query", name: "page", schema: { type: "integer" } },
            ],
          }),
        }),
      ),
    "operation parameters contain duplicate query:page",
  );
  assertThrows(
    () =>
      renderProviderClient(
        "fixture",
        fixtureDocument({
          "/orphan": operation("orphanGet", {
            parameters: [{ in: "path", name: "id", schema: { type: "string" } }],
          }),
        }),
      ),
    "path parameter id has no matching path capture",
  );
  assertThrows(
    () =>
      renderProviderClient(
        "fixture",
        fixtureDocument({
          "/media": {
            get: {
              operationId: "duplicateMediaGet",
              responses: {
                "200": {
                  description: "ambiguous normalized media",
                  content: {
                    "application/json": { schema: { type: "object" } },
                    "Application/JSON; profile=second": { schema: { type: "object" } },
                  },
                },
              },
            },
          },
        }),
      ),
    "duplicates normalized media type",
  );
  assertThrows(
    () =>
      renderProviderClient(
        "fixture",
        fixtureDocument({
          "/deep": operation("deepGet", {
            parameters: [{
              in: "query",
              name: "filter",
              style: "deepObject",
              explode: false,
              schema: {
                type: "object",
                additionalProperties: false,
                properties: { state: { type: "string" } },
              },
            }],
          }),
        }),
      ),
    "deepObject query parameter filter requires explode: true",
  );
  assertThrows(
    () =>
      renderProviderClient(
        "fixture",
        fixtureDocument({
          "/deep": operation("deepGet", {
            parameters: [{
              in: "query",
              name: "filter",
              style: "deepObject",
              explode: true,
              schema: {
                type: "object",
                additionalProperties: false,
                properties: { nested: { type: "object" } },
              },
            }],
          }),
        }),
      ),
    "deepObject query parameter filter requires a closed flat primitive object schema",
  );
});

Deno.test("supported deepObject query schemas retain exact serialization metadata", () => {
  const source = renderProviderClient(
    "fixture",
    fixtureDocument({
      "/deep": operation("deepGet", {
        parameters: [{
          in: "query",
          name: "filter",
          style: "deepObject",
          explode: true,
          schema: {
            type: "object",
            additionalProperties: false,
            properties: { page: { type: "integer" }, state: { type: "string" } },
          },
        }],
      }),
    }),
  );

  assert(
    source.includes('{"name":"filter","style":"deepObject","explode":true}'),
    "deepObject wire metadata changed",
  );
  assert(source.includes('"filter"?: {'), "deepObject input shape was not retained");
});

Deno.test("wildcard captures synthesize path inputs without rewriting declared query parameters", () => {
  const document = parseOpenApiDocument(
    JSON.stringify({
      openapi: "3.0.3",
      info: { title: "Wildcard fixture", version: "1" },
      paths: {},
      "x-ms-paths": {
        "/files/*artifact": {
          get: {
            operationId: "filesGet",
            parameters: [{
              in: "query",
              name: "artifact",
              required: true,
              description: "Mislocated upstream wildcard parameter",
              schema: { type: "string" },
            }],
            responses: { "204": { description: "none" } },
          },
        },
      },
      components: { schemas: {} },
    }),
    "wildcard-fixture",
  );
  const source = renderProviderClient("fixture", document);

  assert(
    source.includes(
      "path: {\n    /**\n     * Path capture synthesized from an upstream route missing its parameter object.",
    ),
    "missing wildcard path input was not synthesized",
  );
  assertEquals(count(source, '"artifact": string;'), 2);
  assert(
    source.includes("query: {\n    /**\n     * Mislocated upstream wildcard parameter"),
    "declared query parameter documentation was rewritten",
  );
  assert(source.includes('path: "/files/{artifact}"'), "wildcard route was not normalized");
  assert(
    source.includes('pathParameters: [{"name":"artifact","multiSegment":true}]'),
    "wildcard path metadata was not emitted",
  );
  assert(
    source.includes(
      'queryParameters: [{"name":"artifact","style":"form","explode":true}]',
    ),
    "declared query metadata was dropped",
  );
});

Deno.test("wire media, no-content, headers, and generated-safe options agree with runtime contract", () => {
  const source = renderProviderClient(
    "fixture",
    fixtureDocument({
      "/media": {
        post: {
          operationId: "mediaPost",
          requestBody: {
            required: true,
            content: {
              "application/octet-stream": {
                schema: {
                  type: "object",
                  properties: { attachment: { type: "string", format: "binary" } },
                },
              },
              "application/vnd.github.object": {
                schema: { type: "object", properties: { entries: { type: "array" } } },
              },
              "text/plain": {
                schema: { type: "object", properties: { value: { type: "string" } } },
              },
              "Application/JSON; charset=utf-8": {
                schema: { type: "object", properties: { value: { type: "string" } } },
              },
            },
          },
          responses: {
            "200": {
              description: "text",
              headers: { "x-next": { schema: { type: "string" } } },
              content: { "text/html": { schema: { type: "object" } } },
            },
            "201": {
              description: "binary",
              content: { "application/zip": { schema: { type: "object" } } },
            },
            "202": {
              description: "reviewed provider JSON media alias",
              content: {
                "application/vnd.github.object": {
                  schema: { type: "object", properties: { entries: { type: "array" } } },
                },
              },
            },
            "203": {
              description: "parameterized mixed-case JSON",
              content: {
                "Application/JSON; charset=utf-8": {
                  schema: { type: "object", properties: { value: { type: "string" } } },
                },
              },
            },
            "204": {
              description: "invalid upstream body must not escape no-content semantics",
              content: { "application/json": { schema: { type: "object" } } },
            },
            default: {
              description: "default multipart response",
              content: { "multipart/related": { schema: { type: "object" } } },
            },
          },
        },
      },
    }),
  );

  assert(source.includes('RestBody<"application/octet-stream", RestBinary>'), "opaque request");
  assert(
    source.includes('RestBody<"application/vnd.github.object", RestBinary>'),
    "response-only JSON media override does not advertise unsupported request serialization",
  );
  assert(
    source.includes(
      'RestBody<"Application/JSON; charset=utf-8", RestJsonValue<RestRequestValue<',
    ),
    "parameterized mixed-case JSON request classification",
  );
  assert(
    source.includes('RestBody<"text/plain", string>'),
    "text wire media incorrectly retained incompatible object schema",
  );
  assert(
    source.includes(
      'RestResponse<200, string, "text/html", true, { readonly "x-next"?: string }>',
    ),
    "text response/header contract",
  );
  assert(
    source.includes('RestResponse<201, globalThis.Blob, "application/zip", true>'),
    "binary response",
  );
  assert(
    source.includes("RestResponse<202, RestJsonValue<") &&
      source.includes('"application/vnd.github.object", true') &&
      source.includes('"application/vnd.github.object":"json"'),
    "reviewed GitHub object media JSON contract",
  );
  assert(
    source.includes('"Application/JSON; charset=utf-8", true') &&
      source.includes('"Application/JSON; charset=utf-8":"json"'),
    "parameterized mixed-case JSON response contract",
  );
  assert(
    source.includes("RestResponse<204, undefined, undefined, true>"),
    "204 no-content response",
  );
  assert(
    source.includes("RestSuccessfulStatus") && source.includes("RestHttpStatus") &&
      source.includes('globalThis.Blob, "multipart/related", true>') &&
      source.includes('globalThis.Blob, "multipart/related", false>'),
    "default multipart response contract",
  );
  assert(source.includes('"decoders":{"text/html":"text"}'), "text decoder metadata");
  assert(
    source.includes('"multipart/related":"binary"'),
    "multipart response decoder metadata",
  );
  assert(source.includes('"headers":["x-next"]'), "response header metadata");
  assert(source.includes("options?: RestGeneratedRequestOptions"), "safe generated options");
});

Deno.test("content-bearing default responses retain runtime 204 and 205 no-content types", () => {
  const source = renderProviderClient(
    "fixture",
    fixtureDocument({
      "/default-only": {
        get: {
          operationId: "defaultOnlyGet",
          responses: {
            default: {
              description: "default JSON",
              headers: { "x-default": { schema: { type: "string" } } },
              content: { "application/json": { schema: { type: "object" } } },
            },
          },
        },
      },
      "/explicit": {
        get: {
          operationId: "explicitGet",
          responses: {
            "204": {
              description: "explicit no content",
              headers: { "x-explicit": { schema: { type: "string" } } },
            },
            default: {
              description: "default JSON",
              headers: { "x-default": { schema: { type: "string" } } },
              content: { "application/json": { schema: { type: "object" } } },
            },
          },
        },
      },
    }),
  );

  const defaultOnly = typeAliasSource(source, "DefaultOnlyGetResponse");
  assert(
    defaultOnly.includes(
      'RestResponse<204, undefined, undefined, true, { readonly "x-default"?: string }>',
    ),
    "default-only 204 runtime branch",
  );
  assert(
    defaultOnly.includes(
      'RestResponse<205, undefined, undefined, true, { readonly "x-default"?: string }>',
    ),
    "default-only 205 runtime branch",
  );
  assert(
    defaultOnly.includes(
      "RestResponse<Exclude<RestSuccessfulStatus, 204 | 205>, RestJsonValue<",
    ) && defaultOnly.includes('"application/json", true') &&
      defaultOnly.includes(
        "RestResponse<Exclude<RestHttpStatus, RestSuccessfulStatus>, RestJsonValue<",
      ) && defaultOnly.includes('"application/json", false'),
    "default success/failure content representations",
  );

  const explicit = typeAliasSource(source, "ExplicitGetResponse");
  assert(
    explicit.includes(
      'RestResponse<204, undefined, undefined, true, { readonly "x-explicit"?: string }>',
    ),
    "explicit 204 response",
  );
  assert(
    !explicit.includes(
      'RestResponse<204, undefined, undefined, true, { readonly "x-default"?: string }>',
    ),
    "default response duplicated explicit 204",
  );
  assert(
    explicit.includes(
      'RestResponse<205, undefined, undefined, true, { readonly "x-default"?: string }>',
    ),
    "missing default-backed 205 response",
  );
});

Deno.test("schema-less JSON media emits strict JSON projection wrappers", () => {
  const source = renderProviderClient(
    "fixture",
    fixtureDocument({
      "/schema-less": {
        post: {
          operationId: "schemaLessPost",
          requestBody: {
            content: { "application/json": {} },
          },
          responses: {
            "200": {
              description: "schema-less JSON",
              content: { "application/json": {} },
            },
          },
        },
      },
    }),
  );

  const input = typeAliasSource(source, "SchemaLessPostInput");
  assert(
    input.includes(
      'RestBody<"application/json", RestJsonValue<RestRequestValue<unknown>>>',
    ),
    "schema-less request escaped JSON projection",
  );
  const response = typeAliasSource(source, "SchemaLessPostResponse");
  assert(
    response.includes('RestResponse<200, RestJsonValue<unknown>, "application/json", true>'),
    "schema-less response escaped JSON projection",
  );
});

Deno.test("optional route groups retain optional inputs, delimiters, and escaped literals", () => {
  const source = renderProviderClient(
    "fixture",
    fixtureDocument({
      "/projects/{id}/(refs/{owner}/{repo}/)summary": operation("groupedGet", {
        parameters: [
          { in: "path", name: "id", required: true, schema: { type: "string" } },
          { in: "path", name: "owner", required: true, schema: { type: "string" } },
          { in: "path", name: "repo", required: true, schema: { type: "string" } },
        ],
      }),
      "/releases/latest(/)(*suffix)": operation("releaseGet", {
        parameters: [{
          in: "query",
          name: "suffix",
          required: true,
          schema: { type: "string" },
        }],
      }),
      "/search/(-/)code": operation("searchGet"),
      "/odata/Packages\\(Id='{id}'\\)": operation("odataGet", {
        parameters: [{ in: "path", name: "id", required: true, schema: { type: "string" } }],
      }),
    }),
  );

  const groupedInput = typeAliasSource(source, "GroupedGetInput");
  assert(groupedInput.includes('"id": string;'), "required outer path input changed");
  assert(groupedInput.includes('"owner": string;'), "present group owner became optional");
  assert(groupedInput.includes('"repo": string;'), "present group repo became optional");
  assert(groupedInput.includes('"owner"?: never;'), "absent group owner was not prohibited");
  assert(groupedInput.includes('"repo"?: never;'), "absent group repo was not prohibited");
  assert(
    source.includes('path: "/projects/{id}/refs/{owner}/{repo}/summary"'),
    "optional group route changed",
  );
  assert(
    source.includes(
      'pathGroups: [{"start":15,"end":35,"parameters":["owner","repo"]}]',
    ),
    "multi-parameter group metadata changed",
  );
  assert(
    source.includes('path: "/releases/latest/{suffix}"'),
    "optional suffix route changed",
  );
  assert(
    source.includes(
      'pathGroups: [{"start":16,"end":17,"parameters":["suffix"]},{"start":17,"end":25,"parameters":["suffix"]}]',
    ),
    "adjacent slash dependency metadata changed",
  );
  assert(
    typeAliasSource(source, "ReleaseGetInput").includes('"suffix"?: string;'),
    "reclassified optional wildcard input stayed required",
  );
  assert(source.includes('path: "/search/-/code"'), "literal group canonical route changed");
  assert(
    source.includes(
      'pathGroups: [{"start":8,"end":10,"selector":"0","defaultIncluded":true}]',
    ),
    "literal group selector metadata changed",
  );
  assert(
    typeAliasSource(source, "SearchGetInput").includes('"0"?: boolean;'),
    "literal group selector was not exposed in generated input",
  );
  assert(
    source.includes("path: \"/odata/Packages(Id='{id}')\""),
    "escaped literal parentheses were treated as groups",
  );
});

Deno.test("provider-native security schemes and effective requirements remain inspectable", () => {
  const document = parseOpenApiDocument(
    JSON.stringify({
      openapi: "3.0.3",
      info: { title: "Fixture", version: "1" },
      security: [{ bearer: ["write", "read"] }],
      paths: {
        "/secured": operation("securedGet"),
        "/public": {
          get: {
            operationId: "publicGet",
            security: [],
            responses: { "204": { description: "none" } },
          },
        },
      },
      components: {
        schemas: {},
        securitySchemes: {
          bearer: { type: "http", scheme: "bearer", bearerFormat: "token" },
        },
      },
    }),
    "fixture",
  );

  const source = renderProviderClient("fixture", document);
  assert(
    source.includes("fixtureServers: typeof fixtureServerDefinitions = deepFreezeRestMetadata("),
    "server metadata is not runtime immutable",
  );
  assert(
    source.includes("static get servers(): typeof fixtureServers") &&
      source.includes("static get securitySchemes(): typeof fixtureSecuritySchemes") &&
      source.includes("Object.defineProperties(FixtureRestClient, {") &&
      source.includes("servers: { configurable: false }") &&
      source.includes("securitySchemes: { configurable: false }"),
    "class metadata accessors are writable or configurable",
  );
  assert(
    source.includes(
      'fixtureSecuritySchemeDefinitions = {"bearer":{"type":"http","scheme":"bearer","bearerFormat":"token"}} as const',
    ),
    "security scheme metadata",
  );
  assert(source.includes('security: [{"bearer":["read","write"]}]'), "inherited security");
  assert(source.includes("security: []"), "explicit public operation security override");
});

Deno.test("staged validation and manifest swap failures preserve the previous snapshot", async () => {
  const temporaryDirectory = await Deno.makeTempDir({
    dir: Deno.cwd(),
    prefix: ".rest-generator-transaction-",
  });
  const root = new URL(`file://${temporaryDirectory}/`);
  const generated = new URL("generated/", root);
  const manifest = new URL("public-names.json", root);
  const previousSource = "export const snapshot = 'previous';\n";
  const nextSource = "export const snapshot = 'next';\n";
  const previousManifest = '{"version":1,"snapshot":"previous"}\n';
  const nextManifest = '{"version":1,"snapshot":"next"}\n';
  await Deno.mkdir(generated);
  await Deno.writeTextFile(new URL("mod.ts", generated), previousSource);
  await Deno.writeTextFile(manifest, previousManifest);

  try {
    const validationFailure = new Error("injected staged type failure");
    assertEquals(
      await captureRejection(
        replaceGeneratedDirectory(generated, new Map([["mod.ts", nextSource]]), {
          validate: () => Promise.reject(validationFailure),
        }),
      ),
      validationFailure,
    );
    assertEquals(await Deno.readTextFile(new URL("mod.ts", generated)), previousSource);

    const swapFailure = new Error("injected manifest swap failure");
    assertEquals(
      await captureRejection(
        replaceGeneratedDirectory(generated, new Map([["mod.ts", nextSource]]), {
          afterGeneratedSwap: () => {
            throw swapFailure;
          },
          manifest: { file: manifest, source: nextManifest },
          validate: () => Promise.resolve(),
        }),
      ),
      swapFailure,
    );
    assertEquals(await Deno.readTextFile(new URL("mod.ts", generated)), previousSource);
    assertEquals(await Deno.readTextFile(manifest), previousManifest);
    const leftovers: string[] = [];
    for await (const entry of Deno.readDir(root)) {
      if (entry.name.startsWith(".generated-") || entry.name.startsWith(".public-names-")) {
        leftovers.push(entry.name);
      }
    }
    assertEquals(leftovers.length, 0);
  } finally {
    await Deno.remove(root, { recursive: true });
  }
});

function fixtureDocument(paths: Record<string, unknown>) {
  return parseOpenApiDocument(
    JSON.stringify({
      openapi: "3.0.3",
      info: { title: "Fixture", version: "1" },
      paths,
      components: { schemas: {} },
    }),
    "fixture",
  );
}

function operation(operationId: string, extra: Record<string, unknown> = {}) {
  return {
    get: {
      operationId,
      responses: {
        "200": {
          description: "ok",
          content: { "application/json": { schema: { type: "object" } } },
        },
      },
      ...extra,
    },
  };
}

function count(value: string, needle: string): number {
  return value.split(needle).length - 1;
}

function typeAliasSource(source: string, name: string): string {
  const value = extractExportedTypeAliases(source, new Set([name])).get(name);
  if (value === undefined) throw new Error(`Missing generated type alias ${name}`);
  return value;
}

function assertThrows(action: () => unknown, message: string): void {
  try {
    action();
  } catch (error) {
    if (error instanceof Error && error.message.includes(message)) return;
    throw error;
  }
  throw new Error(`Expected error containing ${JSON.stringify(message)}`);
}

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

function assertEquals(actual: unknown, expected: unknown): void {
  if (actual !== expected) {
    throw new Error(`Expected ${JSON.stringify(expected)}, received ${JSON.stringify(actual)}`);
  }
}

async function captureRejection(value: Promise<unknown>): Promise<unknown> {
  try {
    await value;
  } catch (error) {
    return error;
  }
  throw new Error("Expected promise to reject");
}
