// @generated by codegen/generate-all.ts. DO NOT EDIT.
// OpenAPI source: https://gitlab.com/gitlab-org/gitlab/-/raw/v18.11.11-ee/doc/api/openapi/openapi_v2.yaml
// OpenAPI SHA-256: sha256:4ec241f083a00372d2eb1629b2cac0b1877463e453d2a961c31057a99206ed4a
// Schema license: no separate license evidence recorded
// Third-party source notice: THIRD_PARTY_NOTICES.md
export * from "./GitLabRestClient.ts";
