// @generated by codegen/generate-all.ts. DO NOT EDIT.
/** An HTTP method represented by the normalized provider specifications. */
export type RestMethod = "DELETE" | "GET" | "HEAD" | "OPTIONS" | "PATCH" | "POST" | "PUT";

/** A media-type-tagged request body generated from an OpenAPI request body. */
export type RestBody<TMediaType extends string, TValue> = {
  mediaType: TMediaType;
  value: TValue;
};

export type RestPathParameter = {
  name: string;
  multiSegment?: boolean;
};

/** A parameter-dependent substring of a generated provider route. */
export type RestPathGroup = {
  /** Inclusive UTF-16 offset in `RestOperation.path`. */
  start: number;
  /** Exclusive UTF-16 offset in `RestOperation.path`. */
  end: number;
  /** Values which must either all be present or all be absent. */
  parameters?: readonly string[];
  /** Generated selector for a literal-only optional provider route group. */
  selector?: string;
  /** Selection used when a literal-only group selector is omitted. */
  defaultIncluded?: boolean;
};

export type RestQueryParameter = {
  name: string;
  style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
  explode?: boolean;
  allowReserved?: boolean;
};

/** Decoder modes emitted from generated response media metadata. */
export type RestGeneratedDecodeMode = "binary" | "json" | "text";

export type RestOperationResponse = {
  status: number | "default";
  mediaTypes: readonly string[];
  /** Generated decoder selection keyed by declared response media type. */
  decoders?: Readonly<Record<string, RestGeneratedDecodeMode>>;
  /** Generated response header names retained in the typed response envelope. */
  headers?: readonly string[];
};

/** Provider-native OpenAPI security requirement: scheme name to required scopes. */
export type RestSecurityRequirement = Readonly<Record<string, readonly string[]>>;

/** Runtime metadata emitted beside every generated operation. */
export type RestOperation = {
  id: string;
  method: RestMethod;
  path: string;
  server?: string;
  pathParameters?: readonly RestPathParameter[];
  pathGroups?: readonly RestPathGroup[];
  queryParameters?: readonly RestQueryParameter[];
  requestMediaTypes?: readonly string[];
  responses: readonly RestOperationResponse[];
  /** Effective operation security. Undefined means unspecified; [] explicitly disables auth. */
  security?: readonly RestSecurityRequirement[];
};

/** Operation context passed through request hooks, including arbitrary raw Fetch methods. */
export type RestRequestOperation = Omit<RestOperation, "method"> & {
  method: string;
};

export type RestOperationInput = {
  path?: Readonly<Record<string, unknown>>;
  pathGroups?: Readonly<Record<string, boolean>>;
  query?: Readonly<Record<string, unknown>>;
  headers?: Readonly<Record<string, unknown>>;
  body?: RestBody<string, unknown>;
};
