// @generated by codegen/generate-all.ts. DO NOT EDIT.
import type { RestRequestOperation } from "./operation.ts";

export type RestParseMode =
  | "arrayBuffer"
  | "auto"
  | "blob"
  | "bytes"
  | "json"
  | "none"
  | "response"
  | "stream"
  | "text";

export type RestRequestOptions = Omit<RequestInit, "body" | "headers" | "method"> & {
  /** Override the client or operation base URL for this request. */
  baseUrl?: string | URL;
  /** Override the generated request body. */
  body?: BodyInit | null;
  /** Additional or overriding request headers. */
  headers?: HeadersInit;
  /** Content type for an overridden body. */
  mediaType?: string;
  /** Override automatic response parsing. `stream` returns a caller-owned, signal-bound stream. */
  parseAs?: RestParseMode;
  /** Additional query values not declared by the specification. */
  query?: Readonly<Record<string, unknown>>;
  /** Override the client's HTTP-error behavior. */
  throwOnError?: boolean;
};

/** Request options exposed by generated methods, which retain their generated response body type. */
export type RestGeneratedRequestOptions = Omit<RestRequestOptions, "parseAs"> & {
  readonly parseAs?: never;
};

export type MaybePromise<T> = Promise<T> | T;

/** Immutable context shared across request authentication and lifecycle hooks. */
export type RestRequestContext = {
  readonly signal?: AbortSignal;
  readonly url: string;
};

export type RestHeadersProvider = (
  operation: RestRequestOperation,
  context: RestRequestContext,
) => MaybePromise<HeadersInit | undefined>;

export type RestClientOptions = {
  /** Provider API root, including any required path prefix such as `/api/v1`. */
  baseUrl: string | URL;
  /** Default headers or a lazy provider applied to the final request target. */
  headers?: HeadersInit | RestHeadersProvider;
  /** Query values included with every request. */
  query?: Readonly<Record<string, unknown>>;
  /** Injectable Fetch implementation for custom transports. */
  fetch?: typeof globalThis.fetch;
  /** Transform or replace a native Request before configured/lazy default headers are applied. */
  beforeRequest?: (
    request: Request,
    operation: RestRequestOperation,
    context: RestRequestContext,
  ) => MaybePromise<Request>;
  /** Observe or replace the native Response before parsing. */
  afterResponse?: (
    response: Response,
    request: Request,
    operation: RestRequestOperation,
    context: RestRequestContext,
  ) => MaybePromise<Response>;
  /** Throw RestApiError for non-2xx responses instead of returning their typed union member. */
  throwOnError?: boolean;
  /** Honor absolute operation-level servers such as GitHub's uploads endpoint. */
  useOperationServers?: boolean;
  /** Forward configured/lazy headers to all final targets or only the configured base origin. */
  headerForwarding?: "all" | "same-origin";
};
